version: '3'
services:
  chatterbox-server:
    image: abirbanerjee/chatterbox-server
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    restart: always
  chatterbox-public:
    image: abirbanerjee/chatterbox-public
    volumes:
      - /usr/src/app/public/
    ports:
      - 3000:3000